version: '3.8'

services:
  spark-master:
    build: .
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results

  spark-worker:
    build: .
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
